# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_heizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('published', models.BooleanField(default=True)),
                ('id_inclass', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='task/images/', verbose_name='image-section')),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='task/images/', verbose_name='image-type1')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='task/images/', verbose_name='image-type2')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType2Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='task2')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.TaskType2', verbose_name='task2-task')),
            ],
        ),
        migrations.AddField(
            model_name='tasktype2',
            name='variant_true',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.TaskType2Variant', verbose_name='variant-true'),
        ),
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_section', to='taskapp.TaskSection'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_type', to='taskapp.TaskType'),
        ),
    ]
