# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20161029_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heizer',
        ),
        migrations.DeleteModel(
            name='Zentek',
        ),
    ]
