# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20161029_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype1',
            name='explanation_to_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasktype2',
            name='explanation_to_answer',
            field=models.TextField(blank=True),
        ),
    ]
