# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_auto_20161030_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktype1',
            old_name='explanation_to_answer',
            new_name='explanation',
        ),
        migrations.RenameField(
            model_name='tasktype2',
            old_name='explanation_to_answer',
            new_name='explanation',
        ),
    ]
