# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0011_sectiontr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiontree',
            name='parent',
        ),
        migrations.DeleteModel(
            name='SectionTree',
        ),
    ]
