# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0012_auto_20161114_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionTr',
            new_name='SectionTree',
        ),
    ]
