# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0013_auto_20161114_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype1',
            name='explanation_img',
            field=models.ImageField(blank=True, null=True, upload_to='task/images/', verbose_name='image-type1-explanation'),
        ),
        migrations.AddField(
            model_name='tasktype2',
            name='explanation_img',
            field=models.ImageField(blank=True, null=True, upload_to='task/images/', verbose_name='image-type1-explanation'),
        ),
    ]
