# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0014_auto_20161117_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktype1',
            old_name='explanation_img',
            new_name='explanation_image',
        ),
        migrations.RemoveField(
            model_name='tasktype2',
            name='explanation_img',
        ),
        migrations.AddField(
            model_name='tasktype2',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='task/images/', verbose_name='image-type1-explanation'),
        ),
    ]
