# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0015_auto_20161117_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionTree',
            new_name='TaskSectionTree',
        ),
    ]
