# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0016_auto_20161120_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_section', to='taskapp.TaskSectionTree'),
        ),
    ]
