# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0017_auto_20161120_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskSection',
            new_name='TaskSectionOld',
        ),
    ]
