# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0018_auto_20161120_2304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskSectionTree',
            new_name='TaskSection',
        ),
    ]
