# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0019_auto_20161120_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksection',
            name='custom_view_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
